# Generated by Django 4.2.11 on 2024-04-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='acknowledgment_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quality_rating',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='items',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(),
        ),
    ]
